SELECT * FROM customer limit 10

-- total revenue generated by male and female customers?

SELECT gender ,SUM(purchase_amount) as revenue
FROM customer
group by gender

-- which customer used a discount but still spent more than the average purchase amount?

SELECT customer_id,purchase_amount
FROM customer
where discount_applied = 'yes' and purchase_amount>=(select AVG(purchase_amount) FROM customer)

-- which are the top 5 products with the highest review rating

SELECT
    item_purchased,
    ROUND(AVG(review_rating), 2) AS `Average Product Rating`
FROM customer
GROUP BY item_purchased
ORDER BY AVG(review_rating) DESC
LIMIT 5;

SHOW tables;

-- compare the average purchase amounts between standard and Expresss shipping

SELECT shipping_type,
ROUND(AVG(purchase_amount) ,2)
FROM customer
WHERE shipping_type in ('Standard','Express')
GROUP BY shipping_type

-- do subscribed customers spend more? compare average spend and total revenue between subscribers and non-subscriber

SELECT subscription_status,
COUNT(customer_id) as total_customers,
ROUND(AVG(purchase_amount),2) as avg_spend,
ROUND(SUM(purchase_amount),2) as total_revenue
FROM customer
GROUP BY subscription_status
ORDER BY total_revenue, avg_spend desc;

-- which 5 product have the highest percentage of purchase with discounts applied?

SELECT item_purchased,
ROUND(100 * SUM(CASE WHEN discount_applied = 'yes' THEN 1 ELSE 0 END)/count(*) ,2) as discount_rate
FROM customer
GROUP BY item_purchased
ORDER BY discount_rate desc
LIMIT 5;

/* segment customers into New,Returning and loyal based on their total numbers of previous purchases and show the count of each segment */

with customer_type as (
SELECT customer_id ,previous_purchases,
CASE
	WHEN previous_Purchases = 1 THEN 'New'
	WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
    ELSE 'loyal'
    END as customer_segment
    FROM customer
    )
    
    SELECT customer_segment, COUNT(*) as 'Number of Customer'
     FROM customer_type
     GROUP BY customer_segment
    
    
    -- what are the top 3 most purchased product within each category
    
    with item_counts as (
    SELECT category,
    item_purchased,
    COUNT(customer_id) as total_orders,
    ROW_NUMBER() over(partition by category order by count(customer_id) DESC) as item_rank
    FROM customer 
    GROUP BY category,item_purchased
    )
    
     SELECT item_rank, category, item_purchased, total_orders
     FROM item_counts
WHERE item_rank <=3;
    
    -- are the customers who are repeat buyers(more than 5 previous purchases) also likely to subscribe?
    
    SELECT subscription_status,
	COUNT(customer_id) as repeat_buyer
    FROM customer
    WHERE previous_purchases >= 5
    GROUP BY subscription_status
    
    -- what is the revenue by age group
    
    SELECT age_group,
    SUM(purchase_amount) as total_revenue
    FROM customer
    GROUP BY age_group
    ORDER BY total_revenue desc;
    